# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nubia/sm7250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter nx651j nx651j_eea,$(TARGET_DEVICE)),)

endif
